😛 change execute order

diff --git a/ustat b/ustat
--- a/ustat
+++ b/ustat
@@ -4,50 +4,9 @@
 # cooking by dariusz@porczynski.net mishmash for now ... but working :)
 # main goals: POSIX/GNU/Linux portability, simple and lightweight, used BASH only with a few standard
 # dependiences
+# . /etc/ustat.conf
 
-# selfupdate from github
-case $1 in
-    "update"|"--update"|"install"|"--install")
-    if ps -e >/dev/null 2>&1; then _PS="ps -e"; else _PS="ps"; fi # check what command to show processes
-    process=$($_PS | grep ustat | grep -v grep | grep -v $0)
-    github_archive="https://github.com/visaroy/ustat/archive/refs/heads/master.zip"
-    rm -R /tmp/ustat* > /dev/null 2>&1
-    if ! wget -nv -O /tmp/ustat.zip --no-check-certificate $github_archive; then
-      echo '[NOK] ERROR: there is no file $github_archive on the server... exit'
-      exit 1
-    else
-      unzip -o -d /tmp /tmp/ustat.zip
-      cd /tmp/ustat-master
-      rm /usr/bin/ustat >/dev/null 2>&1
-      rm /etc/init.d/ustat >/dev/null 2>&1
-      [[ -f /etc/ustat.conf ]] && echo "* [ OK ] ustat.conf already in /etc"
-      [[ -f /etc/ustat.conf ]] || cp ./etc/ustat.conf /etc/ustat.conf; echo "* [ OK ] ustat.conf coppied to /etc"
-      [[ -x /usr/bin/ustat ]] && echo "* [ OK ] ustat script already installed"
-      [[ -x /usr/bin/ustat ]] || cp ./ustat /usr/bin/ustat; chmod +x /usr/bin/ustat; echo "* [ OK ] ustat script installed"
-      if [ -x /etc/init.d/ustat ]; then
-        echo "* [ OK ] ustat service already installed, usage: /etc/init.d/ustat start"
-      else
-        cp ./etc/init.d/ustat /etc/init.d/ustat
-        chmod +x /etc/init.d/ustat
-        cd /etc/init.d/
-        update-rc.d -v ustat start 99 3 . stop 99 6 . >/dev/null 2>&1
-        update-rc.d -f ustat defaults 99 >/dev/null 2>&1
-        cd /
-        echo "* [ OK ] ustat service installed, usage: service ustat start|stop|restart"
-      fi
-    fi
-    systemctl restart ustat
-#    /etc/init.d/ustat restart
-    exit 0
-    ;;
-    *)
-    echo -e "* [error] wrong option, try: ustat -h"
-    ;;
-esac
-
-# parse config file
-
-parse_config_file () {
+parse_config_file () { # parse config file
   config="/etc/ustat.conf"
   INFLUXDB_DATABASE=$(sed -nE "/^\[\[outputs\.influxdb\]\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf \
   | grep database \
@@ -55,7 +14,6 @@ parse_config_file () {
   | sed 's/database=//g' \
   | sed 's/"//g' \
   | tr -d ' ')
-  echo "INFLUXDB_DATABASE=$INFLUXDB_DATABASE \r"
 
   INFLUXDB_HOST=$(sed -nE "/^\[\[outputs\.influxdb\]\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf \
   | grep urls \
@@ -65,7 +23,6 @@ parse_config_file () {
   | sed 's/urls=//g' \
   | sed 's/"//g' \
   | tr -d ' ')
-  echo "INFLUXDB_HOST=$INFLUXDB_HOST \r"
 
   INTERVAL=$(sed -nE "/^\[agent\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf \
   | grep " interval" \
@@ -73,7 +30,6 @@ parse_config_file () {
   | sed 's/interval=//g' \
   | sed 's/"//g' \
   | tr -d ' ')
-  echo "INTERVAL=$INTERVAL \r"
 
   INTERFACES=$(sed -nE "/^\[\[inputs\.net\]\]/ { :l /^\s*[^#].*/ p; n; /^\[/ q; b l; }" /etc/ustat.conf \
   | grep "interfaces" \
@@ -86,13 +42,12 @@ parse_config_file () {
     NETWORK_INTERFACE=`echo $NETWORK_INTERFACE | tr -d '"()'`
     echo -e "NETWORK_INTERFACE=$NETWORK_INTERFACE"
   done
+  echo "INFLUXDB_DATABASE=$INFLUXDB_DATABASE INFLUXDB_HOST=$INFLUXDB_HOST INTERVAL=$INTERVAL"
 }
 
-# . /etc/ustat.conf
-# database based on mac address for now, TODO: crypted, based on UUID and/or hardware IDs
-read_eth0_mac_address=`cat /sys/class/net/$NETWORK_INTERFACE/address | tr ':' ' ' | tr '\n' ' ' | sed 's/[[:space:]]//g'`
-
 initialize_matrics () { # opendtsdb
+# database based on mac address for now, TODO: crypted, based on UUID and/or hardware IDs
+  read_eth0_mac_address=`cat /sys/class/net/$NETWORK_INTERFACE/address | tr ':' ' ' | tr '\n' ' ' | sed 's/[[:space:]]//g'`
   $read_eth0_mac_address
 #  /usr/share/opentsdb/bin/tsdb mkmetric $eth0_mac_address.proc.loadavg.1m
 #  /usr/share/opentsdb/bin/tsdb mkmetric $eth0_mac_address.proc.loadavg.5m
@@ -178,69 +133,115 @@ write_loop () {
 }
 
 ustat_help () {
-  echo -e "usage: ustat <-option>\n\
-  -b \t\t\t - verbose\n\
-  -c \t\t\t - create database \n\
-  -d \t\t\t - drop database\n\
-  -i [database] \t - database name\n\
-  -o [network_interface] \t network interface eg. -o eth0\n\
-  -p \t\t\t read proc load\n\
-  -r \t\t\t read database\n\
-  -s \t\t\t show databases\n\
-  -t [interval] \t interval in seconds eg. -t 5\n\
-  -w \t\t\t write a point to influxdb database\n\
+  echo -e "usage: ustat <option>|[options] [value]\n\
+  -b \t\t\t\t - verbose\n\
+  -c \t\t\t\t - create database \n\
+  -d \t\t\t\t - drop database\n\
+  -i [database] \t\t - database name\n\
+  -o [network_interface] \t - network interface eg. -o eth0\n\
+  -p \t\t\t\t - read proc load\n\
+  -r \t\t\t\t - read database\n\
+  -s \t\t\t\t - show databases\n\
+  -t [interval] \t\t - interval in seconds eg. -t 5\n\
+  -w \t\t\t\t - write a point to influxdb database\n\
   --update|update|--install \t - update ustat files and service (or install if not exists)
   Examples:\n\
   ustat -w \t\t\t - write 1 network metric every INTERVAL time to default database from /etc/ustat.conf \n\
-  ustat -i data1 -w \t\t\t - write
+  ustat -i data1 -w \t\t - write metric point to data1 database \n\
+  ustat -k tagKey -v tagValue -K fieldKey -V fieldValue -w \n\
+  ustat update \n
 "
 }
 
-parse_config_file
+ustat_install () { # install or selfupdate from github
+  if ps -e >/dev/null 2>&1; then _PS="ps -e"; else _PS="ps"; fi # check what command to show processes
+  process=$($_PS | grep ustat | grep -v grep | grep -v $0)
+  github_archive="https://github.com/visaroy/ustat/archive/refs/heads/master.zip"
+  rm -R /tmp/ustat* > /dev/null 2>&1
+  if ! wget -nv -O /tmp/ustat.zip --no-check-certificate $github_archive; then
+    echo '[NOK] ERROR: there is no file $github_archive on the server... exit'
+    exit 1
+  else
+    unzip -o -d /tmp /tmp/ustat.zip
+    cd /tmp/ustat-master
+    rm /usr/bin/ustat >/dev/null 2>&1
+    rm /etc/init.d/ustat >/dev/null 2>&1
+    [[ -f /etc/ustat.conf ]] && echo "* [ OK ] ustat.conf already in /etc"
+    [[ -f /etc/ustat.conf ]] || cp ./etc/ustat.conf /etc/ustat.conf; echo "* [ OK ] ustat.conf coppied to /etc"
+    [[ -x /usr/bin/ustat ]] && echo "* [ OK ] ustat script already installed"
+    [[ -x /usr/bin/ustat ]] || cp ./ustat /usr/bin/ustat; chmod +x /usr/bin/ustat; echo "* [ OK ] ustat script installed"
+    if [ -x /etc/init.d/ustat ]; then
+      echo "* [ OK ] ustat service already installed, usage: /etc/init.d/ustat start"
+    else
+      cp ./etc/init.d/ustat /etc/init.d/ustat
+      chmod +x /etc/init.d/ustat
+      cd /etc/init.d/
+      update-rc.d -v ustat start 99 3 . stop 99 6 . >/dev/null 2>&1
+      update-rc.d -f ustat defaults 99 >/dev/null 2>&1
+      cd /
+      echo "* [ OK ] ustat service installed, usage: service ustat start|stop|restart"
+    fi
+    exit 0
+  fi
+  systemctl restart ustat
+#    /etc/init.d/ustat restart
+}
 
-while getopts 'b c d h i: o p r s t: w' opt
-do
-  case "${opt}" in
-    b ) _VERBOSE="true"
-    ;;
-    c )
-    DATABASE_FOUND="false"
-    while [[ $DATABASE_FOUND = "false" ]]; do
+ustat_run () {
+  while getopts 'b c d h i: o p r s t: w' opt
+  do
+    case "${opt}" in
+      b ) _VERBOSE="true"
+      ;;
+      c )
+      DATABASE_FOUND="false"
+      while [[ $DATABASE_FOUND = "false" ]]; do
+        read_database
+        create_database
+      done
+      ;;
+      d ) drop_database
+      ;;
+      h ) ustat_help
+      ;;
+      i ) INFLUXDB_DATABASE="$OPTARG"; echo "INFLUXDB_DATABASE=$OPTARG"
+      ;;
+      o ) read_network_stats $NETWORK_INTERFACE; echo -e "TIMESTAMP=$TIMESTAMP rx=$rx tx=$tx"
+      ;;
+      p ) read_proc_load
+      ;;
+      r ) read_database
+      ;;
+      s ) show_databases
+      ;;
+      t ) interval="$OPTARG"
+      ;;
+      w )
       read_database
       create_database
-    done
+      while true; do
+        read_network_stats $NETWORK_INTERFACE
+        echo -e "INFLUXDB_DATABASE=$INFLUXDB_DATABASE measurement=$INFLUXDB_DATABASE tag1=$NETWORK_INTERFACE \
+        rx=$rx tx=$tx TIMESTAMP=$TIMESTAMP"
+        write_a_point_to_influxdb $INFLUXDB_DATABASE $INFLUXDB_DATABASE $NETWORK_INTERFACE $rx $TIMESTAMP
+        sleep $INTERVAL
+      done
+      ;;
+      :) echo "Option -$OPTARG requires an argument." >&2
+      ;;
+      *)  ustat_help; exit 0
+      ;;
+    esac
+  done
+  shift $((OPTIND-1))
+}
+
+case $1 in
+    "update"|"--update"|"install"|"--install")
+    ustat_install
     ;;
-    d ) drop_database
+    *)
+    parse_config_file
+    ustat_run
     ;;
-    h ) ustat_help
-    ;;
-    i ) INFLUXDB_DATABASE="$OPTARG"; echo "INFLUXDB_DATABASE=$OPTARG"
-    ;;
-    o ) read_network_stats $NETWORK_INTERFACE; echo -e "TIMESTAMP=$TIMESTAMP rx=$rx tx=$tx"
-    ;;
-    p ) read_proc_load
-    ;;
-    r ) read_database
-    ;;
-    s ) show_databases
-    ;;
-    t ) interval="$OPTARG"
-    ;;
-    w )
-    read_database
-    create_database
-    while true; do
-      read_network_stats $NETWORK_INTERFACE
-      echo -e "INFLUXDB_DATABASE=$INFLUXDB_DATABASE measurement=$INFLUXDB_DATABASE tag1=$NETWORK_INTERFACE \
-      rx=$rx tx=$tx TIMESTAMP=$TIMESTAMP"
-      write_a_point_to_influxdb $INFLUXDB_DATABASE $INFLUXDB_DATABASE $NETWORK_INTERFACE $rx $TIMESTAMP
-      sleep $INTERVAL
-    done
-    ;;
-    :) echo "Option -$OPTARG requires an argument." >&2
-    ;;
-    * )  ustat_help; exit 0
-    ;;
-  esac
-done
-shift $((OPTIND-1))
+esac
